title: Models matemàtics
description: Models matemàtics discrets aplicats a la Biologia i la Biotecnologia
lang: ca
url: https://biocomputing-teaching.github.io
baseurl: /Models-Matematics
repository: Biocomputing-Teaching/Models-Matematics
copyright:
  start_year: 2024
  holder: Biocomputing-Teaching

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge

permalink: pretty
timezone: Europe/Madrid

defaults:
  - scope:
      path: ""
    values:
      layout: default
